const SerialPort = require('serialport')
const Readline = require('@serialport/parser-readline')
const port = new SerialPort('com4')
const parser = new Readline()
port.pipe(parser)
parser.on('data', console.log)
port.write('ROBOT PLEASE RESPOND\n')